package org.example.model;

public record Current(Integer last_updated_epoch,
                      String last_updated,
                      Double temp_c,
                      Double temp_f,
                      Double is_day,
                      Condition condition,
                      Integer wind_mph,
                      Double wind_kph,
                      Double wind_degree,
                      String wind_dir,
                      Double pressure_mb,
                      Double pressure_in,
                      Double precip_mm,
                      Integer precip_in,
                      Integer humidity,
                      Integer cloud,
                      Double feelslike_c,
                      Double feelslike_f,
                      Double windchill_c,
                      Double windchill_f,
                      Double heatindex_c,
                      Double heatindex_f,
                      Double dewpoint_c,
                      Double dewpoint_f,
                      Integer vis_km,
                      Integer vis_miles,
                      Integer uv,
                      Double gust_mph,
                      Double gust_kph,
                      AirQuality airQuality
) {
}
